### ISSUE TITLE
FAST hub server unreachable for download

### ISSUE THREAD

**Issue by e-platini** [smistad/FAST#207]
When executing in python code:
`model = fast.DataHub().download('nuclei-segmentation-model')`
or in command line:
`runPipeline --datahub breast-tumour-segmentation --file /path/to/WSI`

I get the error:
`Traceback (most recent call last):
  File "C:\Users\etiennp\PycharmProjects\RACE\utils\npy_dataset_no_render.py", line 14, in <module>
    model = fast.DataHub().download('nuclei-segmentation-model')
  File "C:\Users\etiennp\PycharmProjects\venvs\venv3810\lib\site-packages\fast\fast.py", line 18982, in download
    return _fast.DataHub_download(self, itemID, force)
RuntimeError: Failed to retrieve data from FAST DataHub.
Server could be down, or you may have no internet access.
Please try again later.`

I do have a working internet connection and this behavior was repeated by someone else on another computer.

**System:**
- Windows 11
- FAST v4.8.0
- Python 3.8.10

**Comment by andreped** [comment]
@e-platini I think the FAST Data hub is down (see image below).

Sadly, @smistad will be away for a while, so I am not sure when this will be fixed.

<img width="1790" alt="Screenshot 2024-06-04 at 18 54 43" src="https://github.com/smistad/FAST/assets/29090665/1077092e-e999-4d6c-a3e8-5adabf103bdc">

**Comment by e-platini** [comment]
@andreped that's what I was afraid of... Thanks for the answer
